<a href="https://colab.research.google.com/github/Ajay0110/Assignments/blob/main/Programming_Assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a Python Program to Add Two Matrices?

In [3]:
x = [[1,7,3],
    [4 ,3,6],
    [7 ,6,9]]
y = [[5,4,1],
    [4,7,3],
    [4,3,7]]

sum = [[x[i][j] + y[i][j]  for j in range(len(x[0]))] for i in range(len(x))]

for i in sum:
   print(i)

[6, 11, 4]
[8, 10, 9]
[11, 9, 16]


2. Write a Python Program to Multiply Two Matrices?

In [5]:
# 3X3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
sol = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           sol[i][j] += X[i][k] * Y[k][j]

for i in sol:
   print(i)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


3. Write a Python Program to Transpose a Matrix?

In [11]:
import numpy as np
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
print(np.transpose(X))

[[12  4  7]
 [ 7  5  8]
 [ 3  6  9]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [14]:
string_1 = str(input("Enter a string: "))
words = string_1.split()
words.sort()
for word in words:
   print(word)

Enter a string: Dragon Ball Super is the best manga
Ball
Dragon
Super
best
is
manga
the


5. Write a Python Program to Remove Punctuation From a String?

In [2]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
string = "Alas! India lost the match & disqualified from T20!!!!!!!."
str2 = ""
for i in string:
   if i not in punctuations:
       str2 = str2 + i
print(str2)

Alas India lost the match  disqualified from T20
